server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: AWS_WebService

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQLDB_USERNAME}
    url: jdbc:mysql://localhost:3306/aws
    password: ${MYSQLDB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect