server:
  port: 8080
  servlet:
    encoding:
      force-response: true

spring:
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  config:
    import: optional:file:.env[.properties]
  application:
    name: AWS_WebService

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQLDB_USERNAME}
    url: jdbc:mysql://localhost:3306/aws
    password: ${MYSQLDB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
            # 보통 "{baseUrl}/login/oauth2/code/google"처럼 {baseUrl} 표현을 쓰지만,
            # 예시에서는 localhost:8080을 직접 명시
            redirect-uri: http://localhost:8080/login/oauth2/code/google

            # authorization_code가 기본값이긴 하지만, 명시해주는 편이 좋습니다.
            authorization-grant-type: authorization_code

            # 구글 기본 scope가 openid, profile, email 인데, openid 제외하려면 아래처럼 오버라이딩
            scope:
              - profile
              - email

            # 기본값은 client_secret_basic이지만, 필요한 경우 명시 가능
            # 구글은 대부분 client_secret_basic 또는 client_secret_post를 지원합니다.
            client-authentication-method: client_secret_basic
          naver:
            client-id: ${NAVER_OAUTH_CLIENT_ID}
            client-secret: ${NAVER_OAUTH_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            # scope를 한 줄에 쉼표로 구분하거나, 아래처럼 리스트로도 표현할 수 있습니다.
            scope: name,email,profile_image
            # scope:
            #   - name
            #   - email
            #   - profile_image
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response